[package]
name = "volt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speculate = "0.1.2"
volt-derive = { path = "../volt-rs-derive" }
